services:
  ethglobalprojectanalysis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - PLAUSIBLE_API_HOST=${PLAUSIBLE_API_HOST}
    container_name: ethglobalprojectanalysis
    restart: unless-stopped
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - POCKETBASE_URL=${POCKETBASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    ports:
      - '8090:8090'
    volumes:
      - ./ethglobalprojectanalysis/pb_data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      start_period: 5s
      interval: 15s
      timeout: 15s
      retries: 3
